In [1]:
import pandas as pd

df= pd.read_csv('GB_videos_data.csv')
df.head()

,Unnamed: 0,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,0,aHzKJOC19SU,Milan 0-3 Inter | Inter Go Four Points Clear w...,2021-02-21T17:07:45Z,UCBJeMCIeLQos7wacox4hmLQ,Serie A,17,21.22.02,Ronaldo|Serie A|Dybala|highlights|Juventus|AC ...,3074832,64812,1759,4797,https://i.ytimg.com/vi/aHzKJOC19SU/default.jpg,False,False,Inter breezed past Milan in the derby to go fo...
1,1,-yI7PU5Sxj0,PE With Joe 2021 | Monday 22nd Feb,2021-02-22T09:29:11Z,UCAxW1XT0iEJo0TYlRfn6rYQ,The Body Coach TV,17,21.22.02,the body coach|Joe wicks|joe wix|the bodycoach...,92847,4809,140,362,https://i.ytimg.com/vi/-yI7PU5Sxj0/default.jpg,False,False,
2,2,vMcB2TcqD-A,Cards Against Humanity PHAN EDITION!,2021-02-21T20:29:11Z,UCHUE4ypXKp7ZkmdWbGJNgJg,AmazingPhil,22,21.22.02,dan and phil|dan howell|phil lester|funny|card...,511276,110828,114,10328,https://i.ytimg.com/vi/vMcB2TcqD-A/default.jpg,False,False,We play an offensive card game ..created by Da...
3,3,z8eMtJJFSJE,HIGHLIGHTS! David Avanesyan crushes Josh Kelly...,2021-02-21T07:00:30Z,UC_JQGBtA7P0RwkRxd7xpJcA,Sky Sports Boxing,17,21.22.02,sky sports boxing|sky sports boxing stream|box...,266111,2536,115,1454,https://i.ytimg.com/vi/z8eMtJJFSJE/default.jpg,False,False,►SUBSCRIBE http://bit.ly/SSBoxingSubJosh Kelly...
4,4,PYLqcf6SelQ,WHO IS THE BEST COUPLE?!,2021-02-21T06:11:13Z,UCPpATKqmMV-CNRNWYaDUwiA,Alexa Rivera,26,21.22.02,[none],2768920,183604,2567,12930,https://i.ytimg.com/vi/PYLqcf6SelQ/default.jpg,False,False,"This was so crazy, you will never guess who ma..."

In [2]:
df.describe()

,Unnamed: 0,categoryId,view_count,likes,dislikes,comment_count
count,6000.000000,6000.000000,6.000000e+03,6.000000e+03,6000.000000,6.000000e+03
mean,2999.500000,19.247000,1.868725e+06,1.091732e+05,2006.638667,1.001406e+04
std,1732.195139,6.352195,4.085882e+06,2.949394e+05,5683.071561,4.899559e+04
min,0.000000,1.000000,1.969500e+04,0.000000e+00,0.000000,0.000000e+00
25%,1499.750000,17.000000,2.831068e+05,1.028275e+04,182.000000,8.000000e+02
50%,2999.500000,22.000000,6.715085e+05,3.300050e+04,481.000000,2.278000e+03
75%,4499.250000,24.000000,1.771276e+06,9.303300e+04,1514.000000,7.050250e+03
max,5999.000000,28.000000,9.303145e+07,7.028950e+06,127643.000000,1.478805e+06

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         6000 non-null   int64
 1   video_id           6000 non-null   object
 2   title              6000 non-null   object
 3   publishedAt        6000 non-null   object
 4   channelId          6000 non-null   object
 5   channelTitle       6000 non-null   object
 6   categoryId         6000 non-null   int64
 7   trending_date      6000 non-null   object
 8   tags               6000 non-null   object
 9   view_count         6000 non-null   int64
 10  likes              6000 non-null   int64
 11  dislikes           6000 non-null   int64
 12  comment_count      6000 non-null   int64
 13  thumbnail_link     6000 non-null   object
 14  comments_disabled  6000 non-null   bool
 15  ratings_disabled   6000 non-null   bool
 16  description        5922 non-null   object
dtypes: bool(2), int64(6), object(9)
memory usage: 715.0+ KB

In [4]:
df = df.drop_duplicates(subset = ['title'])
df

,Unnamed: 0,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,0,aHzKJOC19SU,Milan 0-3 Inter | Inter Go Four Points Clear w...,2021-02-21T17:07:45Z,UCBJeMCIeLQos7wacox4hmLQ,Serie A,17,21.22.02,Ronaldo|Serie A|Dybala|highlights|Juventus|AC ...,3074832,64812,1759,4797,https://i.ytimg.com/vi/aHzKJOC19SU/default.jpg,False,False,Inter breezed past Milan in the derby to go fo...
1,1,-yI7PU5Sxj0,PE With Joe 2021 | Monday 22nd Feb,2021-02-22T09:29:11Z,UCAxW1XT0iEJo0TYlRfn6rYQ,The Body Coach TV,17,21.22.02,the body coach|Joe wicks|joe wix|the bodycoach...,92847,4809,140,362,https://i.ytimg.com/vi/-yI7PU5Sxj0/default.jpg,False,False,
2,2,vMcB2TcqD-A,Cards Against Humanity PHAN EDITION!,2021-02-21T20:29:11Z,UCHUE4ypXKp7ZkmdWbGJNgJg,AmazingPhil,22,21.22.02,dan and phil|dan howell|phil lester|funny|card...,511276,110828,114,10328,https://i.ytimg.com/vi/vMcB2TcqD-A/default.jpg,False,False,We play an offensive card game ..created by Da...
3,3,z8eMtJJFSJE,HIGHLIGHTS! David Avanesyan crushes Josh Kelly...,2021-02-21T07:00:30Z,UC_JQGBtA7P0RwkRxd7xpJcA,Sky Sports Boxing,17,21.22.02,sky sports boxing|sky sports boxing stream|box...,266111,2536,115,1454,https://i.ytimg.com/vi/z8eMtJJFSJE/default.jpg,False,False,►SUBSCRIBE http://bit.ly/SSBoxingSubJosh Kelly...
4,4,PYLqcf6SelQ,WHO IS THE BEST COUPLE?!,2021-02-21T06:11:13Z,UCPpATKqmMV-CNRNWYaDUwiA,Alexa Rivera,26,21.22.02,[none],2768920,183604,2567,12930,https://i.ytimg.com/vi/PYLqcf6SelQ/default.jpg,False,False,"This was so crazy, you will never guess who ma..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5869,5869,vCd3CCnqqDU,NIGELLA LAWSON So Pretty But CAN SHE MAKE RAMEN?,2021-03-21T14:00:13Z,UCVjlpEjEY9GpksqbEesJnNA,mrnigelng,23,21.23.03,nigel ng|uncle roger|nigel ng comedy,1171280,56051,849,4300,https://i.ytimg.com/vi/vCd3CCnqqDU/default.jpg,False,False,"Niece and nephew, go watch Nephew Nigel podcas..."
5872,5872,tmQYskXD1EQ,YouTube just isn't working for me anymore,2021-03-21T20:03:51Z,UCT7H_xchRHaT9zr5GalIZVA,Evan Edinger,27,21.23.03,youtube|youtube isn't working|youtube is broke...,87798,14205,84,1731,https://i.ytimg.com/vi/tmQYskXD1EQ/default.jpg,False,False,I think I've reached my breaking point with Yo...
5880,5880,le-MZxQYKqA,Solskjaer's Last Chance! Pogba Juve Talks? Man...,2021-03-22T11:00:07Z,UCMmVPVb0BwSIOWVeDwlPocQ,The United Stand,24,21.23.03,Manchester United|Man United|Man Utd|Mancheste...,162650,4775,280,994,https://i.ytimg.com/vi/le-MZxQYKqA/default.jpg,False,False,Man Utd must change under Solskjaer if United ...
5887,5887,CdxEcCHyPdQ,Bloodcurdling Facts That You Wish You Never Kn...,2021-03-19T03:51:11Z,UCFRCiFkWWJN2rO6dsKU9-1A,Jack Neel,27,21.23.03,[none],930098,78452,2748,1874,https://i.ytimg.com/vi/CdxEcCHyPdQ/default.jpg,False,False,► TikTok: https://www.tiktok.com/@fyp► Instagr...
5889,5889,CB6rcej5uXk,Vikkstar's Milk: A Short Story,2021-03-21T20:00:01Z,UCbAZH3nTxzyNmehmTUhuUsA,SidemenShorts,22,21.23.03,Shorts|Sidemen,249881,18682,46,316,https://i.ytimg.com/vi/CB6rcej5uXk/default.jpg,False,False,What other clips do you want to see? Lets us k...

In [5]:
df = df[['title', 'description']]
print(df)
df.columns = ['Title', 'Description']
print(df.columns)

                                                  title  \
0     Milan 0-3 Inter | Inter Go Four Points Clear w...
1                    PE With Joe 2021 | Monday 22nd Feb
2                  Cards Against Humanity PHAN EDITION!
3     HIGHLIGHTS! David Avanesyan crushes Josh Kelly...
4                              WHO IS THE BEST COUPLE?!
...                                                 ...
5869   NIGELLA LAWSON So Pretty But CAN SHE MAKE RAMEN?
5872          YouTube just isn't working for me anymore
5880  Solskjaer's Last Chance! Pogba Juve Talks? Man...
5887  Bloodcurdling Facts That You Wish You Never Kn...
5889                     Vikkstar's Milk: A Short Story

                                            description
0     Inter breezed past Milan in the derby to go fo...
1
2     We play an offensive card game ..created by Da...
3     ►SUBSCRIBE http://bit.ly/SSBoxingSubJosh Kelly...
4     This was so crazy, you will never guess who ma...
...                                                 ...
5869  Niece and nephew, go watch Nephew Nigel podcas...
5872  I think I've reached my breaking point with Yo...
5880  Man Utd must change under Solskjaer if United ...
5887  ► TikTok: https://www.tiktok.com/@fyp► Instagr...
5889  What other clips do you want to see? Lets us k...

[1370 rows x 2 columns]
Index(['Title', 'Description'], dtype='object')

In [6]:
import re
df['cleaned_title'] = df['Title'].apply(lambda x: x.lower())
df['cleaned_title'] = df['cleaned_title'].apply(lambda x: re.sub('[^A-Za-z0-9]+', ' ', x))

C:\Users\rakes\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\rakes\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [7]:
df

,Title,Description,cleaned_title
0,Milan 0-3 Inter | Inter Go Four Points Clear w...,Inter breezed past Milan in the derby to go fo...,milan 0 3 inter inter go four points clear wit...
1,PE With Joe 2021 | Monday 22nd Feb,,pe with joe 2021 monday 22nd feb
2,Cards Against Humanity PHAN EDITION!,We play an offensive card game ..created by Da...,cards against humanity phan edition
3,HIGHLIGHTS! David Avanesyan crushes Josh Kelly...,►SUBSCRIBE http://bit.ly/SSBoxingSubJosh Kelly...,highlights david avanesyan crushes josh kelly ...
4,WHO IS THE BEST COUPLE?!,"This was so crazy, you will never guess who ma...",who is the best couple
...,...,...,...
5869,NIGELLA LAWSON So Pretty But CAN SHE MAKE RAMEN?,"Niece and nephew, go watch Nephew Nigel podcas...",nigella lawson so pretty but can she make ramen
5872,YouTube just isn't working for me anymore,I think I've reached my breaking point with Yo...,youtube just isn t working for me anymore
5880,Solskjaer's Last Chance! Pogba Juve Talks? Man...,Man Utd must change under Solskjaer if United ...,solskjaer s last chance pogba juve talks man u...
5887,Bloodcurdling Facts That You Wish You Never Kn...,► TikTok: https://www.tiktok.com/@fyp► Instagr...,bloodcurdling facts that you wish you never kn...
5889,Vikkstar's Milk: A Short Story,What other clips do you want to see? Lets us k...,vikkstar s milk a short story

In [12]:
tf.saved_model.LoadOptions(
    experimental_io_device=None
)

In [14]:
from tensorflow import keras
import tensorflow_hub as hub
import tensorflow_text as text
preprocessor = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1", trainable=True)
def get_bert_embeddings(text, preprocessor, encoder):
    text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
    encoder_inputs = preprocessor(text_input)
    outputs = encoder(encoder_inputs)
    embedding_model = tf.keras.Model(text_input, outputs['pooled_output'])
    sentences = tf.constant([text])
    return embedding_model(sentences)

In [16]:
df['encodings'] = df['cleaned_title'].apply(lambda x: get_bert_embeddings(x, preprocessor, encoder))

C:\Users\rakes\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn import metrics
def preprocess_text():
  text = input()
  text = text.lower()
  text = re.sub('[^A-Za-z0-9]+', ' ', text)
  return text
  
query_text = preprocess_text()
query_encoding = get_bert_embeddings(query_text, preprocessor, encoder)

df['similarity_score'] = df['encodings'].apply(lambda x: metrics.pairwise.cosine_similarity(x, query_encoding)[0][0])
df_results = df.sort_values(by=['similarity_score'], ascending=False)

Action, Hollywood, Thrillers

C:\Users\rakes\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [24]:
df_results

,Title,Description,cleaned_title,encodings,similarity_score
1016,Shadow and Bone | Teaser Trailer | Netflix,"The Shadow Fold. To destroy it, we need a mira...",shadow and bone teaser trailer netflix,"((tf.Tensor(-0.99999577, shape=(), dtype=float...",0.969025
5808,SML Movie: Jeffy!,Jeffy shows up for the first time!We are remak...,sml movie jeffy,"((tf.Tensor(-0.9999986, shape=(), dtype=float3...",0.967630
131,Disney's Cruella | Official Trailer,Brilliant. Bad. A little bit mad. May 2021.Aca...,disney s cruella official trailer,"((tf.Tensor(-0.99999636, shape=(), dtype=float...",0.966278
2621,AMELIA'S COOKING SHOW | CHUNKZ,#AD Amelia is joined in her kitchen by fellow ...,amelia s cooking show chunkz,"((tf.Tensor(-0.99999285, shape=(), dtype=float...",0.964374
4463,Disney’s Cruella | Sneak Peek,"This May, meet the Queen of Mean #Cruella 💋 🖤A...",disney s cruella sneak peek,"((tf.Tensor(-0.99999624, shape=(), dtype=float...",0.962276
...,...,...,...,...,...
3203,Juventus v Porto (3-2) | Visitors win on away ...,10-man Porto pulled off a huge Champion League...,juventus v porto 3 2 visitors win on away goal...,"((tf.Tensor(-0.99904203, shape=(), dtype=float...",0.631276
4116,Knights v Bulldogs Match Highlights | Round 1 ...,Knights co-captain Daniel Saifiti celebrated h...,knights v bulldogs match highlights round 1 20...,"((tf.Tensor(-0.99970746, shape=(), dtype=float...",0.609756
401,Atletico Madrid v Chelsea (0-1) | Giroud score...,Olivier Giroud's magnificent bicycle-kick was ...,atletico madrid v chelsea 0 1 giroud scores am...,"((tf.Tensor(-0.9985671, shape=(), dtype=float3...",0.554765
5013,UEFA Champions League 2020/21 Quarter-Final & ...,Watch the draw for 2020/21 UEFA Champions Leag...,uefa champions league 2020 21 quarter final se...,"((tf.Tensor(-0.9986811, shape=(), dtype=float3...",0.553473
5024,MARJANEYA - Neha Kakkar | Rubina Dilaik & Abhi...,Anshul Garg presents Marjaneya by Neha Kakkar ...,marjaneya neha kakkar rubina dilaik abhinav sh...,"((tf.Tensor(-0.99952936, shape=(), dtype=float...",0.542365

In [26]:
df_results['Title']

1016           Shadow and Bone | Teaser Trailer | Netflix
5808                                    SML Movie: Jeffy!
131                   Disney's Cruella | Official Trailer
2621                       AMELIA'S COOKING SHOW | CHUNKZ
4463                        Disney’s Cruella | Sneak Peek
                              ...
3203    Juventus v Porto (3-2) | Visitors win on away ...
4116    Knights v Bulldogs Match Highlights | Round 1 ...
401     Atletico Madrid v Chelsea (0-1) | Giroud score...
5013    UEFA Champions League 2020/21 Quarter-Final & ...
5024    MARJANEYA - Neha Kakkar | Rubina Dilaik & Abhi...
Name: Title, Length: 1370, dtype: object

In [27]:
df_results.head()

,Title,Description,cleaned_title,encodings,similarity_score
1016,Shadow and Bone | Teaser Trailer | Netflix,"The Shadow Fold. To destroy it, we need a mira...",shadow and bone teaser trailer netflix,"((tf.Tensor(-0.99999577, shape=(), dtype=float...",0.969025
5808,SML Movie: Jeffy!,Jeffy shows up for the first time!We are remak...,sml movie jeffy,"((tf.Tensor(-0.9999986, shape=(), dtype=float3...",0.967630
131,Disney's Cruella | Official Trailer,Brilliant. Bad. A little bit mad. May 2021.Aca...,disney s cruella official trailer,"((tf.Tensor(-0.99999636, shape=(), dtype=float...",0.966278
2621,AMELIA'S COOKING SHOW | CHUNKZ,#AD Amelia is joined in her kitchen by fellow ...,amelia s cooking show chunkz,"((tf.Tensor(-0.99999285, shape=(), dtype=float...",0.964374
4463,Disney’s Cruella | Sneak Peek,"This May, meet the Queen of Mean #Cruella 💋 🖤A...",disney s cruella sneak peek,"((tf.Tensor(-0.99999624, shape=(), dtype=float...",0.962276

In [28]:
df_results.tail()

,Title,Description,cleaned_title,encodings,similarity_score
3203,Juventus v Porto (3-2) | Visitors win on away ...,10-man Porto pulled off a huge Champion League...,juventus v porto 3 2 visitors win on away goal...,"((tf.Tensor(-0.99904203, shape=(), dtype=float...",0.631276
4116,Knights v Bulldogs Match Highlights | Round 1 ...,Knights co-captain Daniel Saifiti celebrated h...,knights v bulldogs match highlights round 1 20...,"((tf.Tensor(-0.99970746, shape=(), dtype=float...",0.609756
401,Atletico Madrid v Chelsea (0-1) | Giroud score...,Olivier Giroud's magnificent bicycle-kick was ...,atletico madrid v chelsea 0 1 giroud scores am...,"((tf.Tensor(-0.9985671, shape=(), dtype=float3...",0.554765
5013,UEFA Champions League 2020/21 Quarter-Final & ...,Watch the draw for 2020/21 UEFA Champions Leag...,uefa champions league 2020 21 quarter final se...,"((tf.Tensor(-0.9986811, shape=(), dtype=float3...",0.553473
5024,MARJANEYA - Neha Kakkar | Rubina Dilaik & Abhi...,Anshul Garg presents Marjaneya by Neha Kakkar ...,marjaneya neha kakkar rubina dilaik abhinav sh...,"((tf.Tensor(-0.99952936, shape=(), dtype=float...",0.542365